name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DATABASE_URL: "https://fake.com/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint
